name: Build
on:
  workflow_dispatch:
  push:
env:
  GODOT_VERSION: 3.5
  GODOT_VERSION_LONG: 3.5.stable
  GODOT_HEADLESS_URL: https://downloads.tuxfamily.org/godotengine/3.5/Godot_v3.5-stable_linux_headless.64.zip
  GODOT_EXPORT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/3.5/Godot_3.5-stable_export_templates.tpz
  BUILD_TYPE: Debug
  ARCH: x64

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: "Linux Latest x64"
            artifact: "Linux-x64.tar.gz"
            bundle_name: "Linux-x64"
            os: ubuntu-latest
          - name: "macOS Latest x64"
            artifact: "macOS-x64.zip"
            bundle_name: "macOS-x64"
            os: macos-latest
          - name: "Windows Latest x64"
            artifact: "windows-x64.zip"
            bundle_name: "windows-x64"
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Deps
        run: |
          echo Install Deps
      - name: Build
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cd CoreGame/ && ./build.sh $RUNNER_OS $ARCH $BUILD_TYPE