name: Build
on:
  workflow_dispatch:
  push:
env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: "Linux Latest x64"
            artifact: "libCoreGame.so"
            bundle_name: "Linux"
            os: ubuntu-latest
          - name: "macOS Latest x64"
            artifact: "libCoreGame.dylib"
            bundle_name: "macOS"
            os: macos-latest
          - name: "Windows Latest x64"
            artifact: "CoreGame.lib"
            bundle_name: "Windows"
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Deps
        run: |
          echo Install Deps
      - name: Configure CMake
        shell: bash
        working-directory: CoreGame
        run: |
          mkdir dist && cd dist
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        shell: bash
        working-directory: CoreGame/dist
        run: |
          cmake --build . -j8
      - name: Prepare Artifacts
        shell: bash
        working-directory: CoreGame/dist/CoreGame
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cd $BUILD_TYPE
            artifactPath=${{ github.workspace }}\\${{ matrix.config.artifact }}
          else 
            artifactPath=${{ github.workspace }}/${{ matrix.config.artifact }}
          fi
          ls -la
          mv ${{ matrix.config.artifact }} ${{ github.workspace }}
          echo "artifactPath=${artifactPath}" >> $GITHUB_ENV
         
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.artifact }}
          path: ${{ env.artifactPath }}
