name: Build
on:
  workflow_dispatch:
  push:
env:
  GODOT_VERSION: 3.5
  GODOT_VERSION_LONG: 3.5.stable
  GODOT_HEADLESS_URL: https://downloads.tuxfamily.org/godotengine/3.5/Godot_v3.5-stable_linux_headless.64.zip
  GODOT_EXPORT_TEMPLATES_URL: https://downloads.tuxfamily.org/godotengine/3.5/Godot_3.5-stable_export_templates.tpz
  BUILD_TYPE: Debug
  ARCH: x64

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: "Linux Latest x64"
            artifact: "libCoreGame.so"
            bundle_name: "Linux"
            os: ubuntu-latest
          - name: "macOS Latest x64"
            artifact: "libCoreGame.dylib"
            bundle_name: "macOS"
            os: macos-latest
          - name: "Windows Latest x64"
            artifact: "CoreGame.dll"
            bundle_name: "Windows"
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Deps
        run: |
          echo Install Deps
      - name: Build
        run: |
          cd CoreGame/
          ./build.sh $RUNNER_OS $ARCH $BUILD_TYPE
      - name: Prepare Artifacts
        shell: bash
        working-directory: ${{ github.workspace }}/CoreGame/dist
        run: |
          ls -la
          cd ${{ matrix.config.bundle_name }}/${{ env.ARCH }}/${{ env.BUILD_TYPE }}/CoreGame/
          mv ${{ matrix.config.artifact }} ${{ github.workspace }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.artifact }}
          path:  ${{ github.workspace }}